name: Rubocop

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs_on: ubuntu_latest
    env:
      BUNDLE_ONLY: rubocop
    
    steps:
      - uses: actions/checkout@v1

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop --parallel
